version: 2
sphinx:
  builder: html
  configuration: source/conf.py
  fail_on_warning: false
# Optionally build your docs in additional formats such as PDF and ePub
formats: all

submodules:
  include:
     - source/src/arm_neon_example
  recursive: true
  
python:
  version: 3.7
