site_name: GoodCommand
nav:
    - Home: index.md
    - linux: linux.md
    - kvm: kvm.md
    - git: git_bash_windows.md
    - fio: fio.md
    - benchmark:
        - cpu: cpu_benchmark.md
        - io: io_benchmark.md
    - 发行版: 
        - redhat: redhat.md
        - ubuntu: ubuntu.md
        - NeoKylin: NeoKylin.md
    - 计算机存储器: 计算机存储器.md
    - 计算机终端: terminal.md
theme: readthedocs