site_name: GoodCommand
nav:
    - Home: index.md
    - linux: linux.md
    - kvm: kvm.md
    - git: git_bash_windows.md
    - fio: fio.md
    - 发行版: 
        - redhat: redhat.md
        - ubuntu: ubuntu.md
    - 计算机存储器: 计算机存储器.md
theme: readthedocs