site_name: GoodCommand
site_author: lixianfa

repo_url: https://github.com/LyleLee/GoodCommand

nav:
    - Home: index.md
    - linux: linux.md
    - kvm: kvm.md
    - git_two_github_account: git_two_github_account.md
    - git_bash_windows: git_bash_windows.md
    - fio: fio.md
    - vdbench: vdbench.md
    - nfs: nfs.md
    - shellcheck: shellcheck.md
    - tldr: tldr.md
    - netstat: netstat.md
    - dstat: dstat.md
    - systemd: systemd.md
    - tzselect: tzselect.md
    - ethtool: ethtool.md
    - nethogs: nethogs.md
    - vim: vim.md
    - gcc: gcc.md
    - vnc: vnc.md
    - benchmark:
        - cpu information: cpuinfo.md
        - cpu spec cpu: cpu_benchmark.md
        - io: io_benchmark.md
        - mem: mem_benchmark.md
    - kernel: linux_kernel.md
    - 发行版: 
        - redhat: redhat.md
        - redhat build kernel[en]: redhat_build_kernel.md
        - redhat build kernel[cn]: redhat_build_kernel_zh.md
        - ubuntu: ubuntu.md
        - ubuntu 软件源: ubuntu_sources_list.md
        - ubuntu 软件包: ubuntu_packages.md
        - ubuntu 桌面环境: ubuntu_desktop.md
        - NeoKylin: NeoKylin.md
    - bug solve:
        - 1670650: 1670650.md
        - nfs_not_respond: nfs_not_respond.md
    - 计算机存储器: 计算机存储器.md
    - 计算机终端: terminal.md
    - raid: raid.md
theme: readthedocs