site_name: GoodCommand
site_author: lixianfa

repo_url: https://github.com/LyleLee/GoodCommand

nav:
    - Home: index.md
    - linux: linux.md
    - kvm: kvm.md
    - docker: docker.md
    - git two github account: git_two_github_account.md
    - git bash windows: git_bash_windows.md
    - git command : git_command.md
    - nfs: nfs.md
    - shellcheck: shellcheck.md
    - tldr: tldr.md
    - netstat: netstat.md
    - dstat: dstat.md
    - systemd: systemd.md
    - time: time.md
    - ethtool: ethtool.md
    - hostnamectl: hostnamectl.md
    - nethogs: nethogs.md
    - tcpdump: tcpdump.md
    - vim: vim.md
    - tmux: tmux.md
    - gcc: gcc.md
    - vnc: vnc.md
    - wget: wget.md
    - install os: install_os.md
    - kernel document: linux_kernel.md
    - shell_program: shell_program.md
    - ARM storage software: arm_storage_stack.md
    - ARM server firmware_update: firmware_update.md
    - update-alternatives.md: update-alternatives.md
    - benchmark tool:
        - fio: fio.md
        - vdbench: vdbench.md
        - perf: perf.md
    - benchmark:
        - cpu information: cpuinfo.md
        - cpu spec cpu: cpu_benchmark.md
        - mem information: meminfo.md
        - mem stream: stream.md
        - mem stream_x86: stream_x86.md
        - mem stream_arm: stream_arm.md
        - io disk imformation: disk_information.md
        - io fio benchmark: io_fio_benchmark.md
    - 发行版: 
        - redhat package: redhat_package.md
        - redhat build kernel[en]: redhat_build_kernel.md
        - redhat build kernel[cn]: redhat_build_kernel_zh.md
        - ubuntu: ubuntu.md
        - ubuntu 软件源: ubuntu_sources_list.md
        - ubuntu 软件包: ubuntu_packages.md
        - ubuntu 桌面环境: ubuntu_desktop.md
        - NeoKylin: NeoKylin.md
        - suse 软件源: suse_local_repo.md
    - bug solve:
        - nfs lock 1670650: nfs_lock.md
        - nfs_not_respond: nfs_not_respond.md
    - interrupts: interrupts.md
    - 计算机存储器: 计算机存储器.md
    - 计算机终端: terminal.md
    - raid级别: raid.md
theme: readthedocs
markdown_extensions:
    - markdown_include.include:
        base_path: docs