site_name: GoodCommand
site_author: lixianfa

repo_url: https://github.com/LyleLee/GoodCommand

nav:
    - Home: index.md
    - alias: alias.md
    - awk: awk.md
    - board_connect: board_connect.md
    - benchmark tool:
        - fio: fio.md
        - vdbench: vdbench.md
        - perf: perf.md
        - memtester: memtester.md
    - benchmark:
        - cpu information: cpuinfo.md
        - cpu speccpu: cpu_speccpu.md
        - cpu compile speccpu: use_patch_compile_speccpu.md
        - cpu coremark: coremark.md
        - mem information: meminfo.md
        - mem stream: stream.md
        - mem stream_x86: stream_x86.md
        - mem stream_arm: stream_arm.md
        - io disk imformation: disk_information.md
        - io fio benchmark: io_fio_benchmark.md
    - BMC : BMC.md
    - bug solve:
        - hdd broken drive: hdd_broken_drive.md
        - nfs lock 1670650: nfs_lock.md
        - nfs_not_respond: nfs_not_respond.md
        - hardware_error_corrected: Hardware_error_corrected.md
        - NIC_name_not_correct: NIC_name_not_correct.md
        - 82599_Bar: 82599_Bar.md
        - bs osd down: bs/ceph_osd_down.md
        - bs ceph ntp: bs/ceph_ntp.md
        - cfd_doc: cfd_doc.md
        - dev_root_not_exist: bs/dev_root_not_exist.md
        - tomcat not start: bs/tomcat_not_start.md
    - ceph: ceph.md
    - devmem: devmem.md
    - dns: dns.md
    - diff: diff.md
    - docker: docker.md
    - dpdk: dpdk.md
    - dstat: dstat.md
    - ethtool: ethtool.md
    - edac-util: edac-util.md
    - firewall: firewall.md
    - fdisk: fdisk.md
    - gcc: gcc.md
    - go: go.md
    - git bash windows: git_bash_windows.md
    - git command : git_command.md
    - git two github account: git_two_github_account.md
    - grub : grub.md
    - hostnamectl: hostnamectl.md
    - install os: install_os.md
    - interrupts: interrupts.md
    - intel_processor: intel_processor.md
    - ip: ip.md
    - iperf: iperf.md
    - ipmitool: ipmitool.md
    - iso_download: iso_download.md
    - kernel:
        - linux内核设计与实现: linux内核设计与实现.md
        - kernel document: linux_kernel.md
        - kernel_module: kernel_module.md
        - kern_levels.h: kern_levels.md
    - kvm: kvm.md
    - linux: linux.md
    - lspci: lspci.md
    - nethogs: nethogs.md
    - netstat: netstat.md
    - nload: nload.md
    - nfs: nfs.md
    - nmap : nmap.md
    - ntfs : ntfs.md
    - numactl : numactl.md
    - raid级别: raid.md
    - script: script.md
    - selinux: selinux.md
    - shell_program: shell_program.md
    - shellcheck: shellcheck.md
    - sftp: sftp.md
    - ssh: ssh.md
    - sshfs: sshfs.md
    - storcli: storcli.md
    - sysrq: sysrq.md
    - systemd: systemd.md
    - tar: tar.md
    - taskset: taskset.md
    - tcpdump: tcpdump.md
    - time: time.md
    - tldr: tldr.md
    - tmux: tmux.md
    - top: top.md
    - update-alternatives: update-alternatives.md
    - upnpc: upnp.md
    - vim: vim.md
    - vnc: vnc.md
    - wget: wget.md
    - 发行版: 
        - 获取内核源码: get_kernel_source.md
        - CentOS build kernel: CentOS_build_kernel.md
        - CentOS package: CentOS_package.md
        - redhat package: redhat_package.md
        - redhat build kernel[en]: redhat_build_kernel.md
        - redhat build kernel[cn]: redhat_build_kernel_zh.md
        - ubuntu: ubuntu.md
        - ubuntu 软件源: ubuntu_sources_list.md
        - ubuntu 软件包: ubuntu_packages.md
        - ubuntu 桌面环境: ubuntu_desktop.md
        - NeoKylin: NeoKylin.md
        - suse 软件源: suse_local_repo.md
    - 服务器:
        - ARM server firmware_update: firmware_update.md
        - ARM storage software: arm_storage_stack.md
        - ARM opensource software: arm_opensource_software.md
        - BMC_DELL_R730: BMC_DELL_R730.md
        - Compare intel kengpeng: compare_intel_kunpeng.md
    - 性能之巅: 性能之巅.md
    - 计算机启动: 计算机启动.md
    - 计算机存储器: 计算机存储器.md
    - 计算机终端: terminal.md

theme: readthedocs
