site_name: GoodCommand
nav:
    - Home: index.md
    - linux: linux.md
    - kvm: kvm.md
    - ceph: ceph测试命令.md
    - git: git_bash_windows.md
    - kylin: kylin_test.md
    - 生成文档: 如何使用生成文档.md
theme: readthedocs